### ISSUE TITLE
How to upgrade older myth to the latest 

### ISSUE THREAD

**Issue by gzuhlwang** [ConsenSys/mythril-classic#1010]
when I use myth to scan my contract, it output the following error, I use solidity compiler ^0.5.6 in my source file:
 **Error: Source file requires different compiler version (current compiler is 0.5.2-develop.2018.12.18+commit.eed46f00.Linux.g++ - note that nightly builds are considered to be strictly less than the released version**

**Comment by norhh** [comment]
Hi @gzuhlwang, That's the problem with the compiler version, the 0.5.6 doesn't seem to be compatible with the source file. try `myth -x filename.sol --solv <some other solc version>` .

**Comment by gzuhlwang** [comment]
@north thanks,I will try.
