### ISSUE TITLE
External call 

### ISSUE THREAD

**Issue by JoranHonig** [ConsenSys/mythril-classic#1012]
## Description
If there is an external call to a precompile then we probably don't want to report an issue at all.

Example contract for which we report a vulnerability: https://github.com/TokenMarketNet/smart-contracts/blob/master/contracts/test/TestSolidityAddressHash.sol

**Comment by b-mueller** [comment]
@JoranHonig @norhh we should also downgrade the severity of external calls to "low", as an external call by itself doesn't cause a vulnerability.

**Comment by JoranHonig** [comment]
@b-mueller external calls that have a static target will already be seen as low severity. 
We can definately make regular external calls low severity as well. But we should open up another issue for that 😅
