### ISSUE TITLE
Build tests for instructions.py

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril-classic#220]
child of #203

**Comment by b-mueller** [comment]
Refactor the tests to test the basic operations of the VM in a unit-test-like fashion instead of using inputs / output files.

Ideally, we should pass the Ethereum VM tests:

https://github.com/ethereum/tests/wiki/VM-Tests

**Comment by JoranHonig** [comment]
This depends on #221  as this will allow us to do more fine grained unit testing.

**Comment by norhh** [comment]
This should be a TC challenge right?( we can also merge this with #207  for the challenge as it is kind of trivial)

**Comment by JoranHonig** [comment]
Closing this because this is largely covered by the consensus tests, other aspects should dynamically be added in the future
