### ISSUE TITLE
Refactor: Rebuild laser and mythril to work with callbacks[MYTHC-3]

### ISSUE THREAD

**Issue by JoranHonig** [ConsenSys/mythril-classic#226]
## Description
Currently, laser-ethereum ( the symbolic analysis backend ) performs symbolic execution on a smart contract and the result of this execution (the statespace) is passed to analysis modules to be analyzed.

In the future, we want to remodel the analysis of smart contracts to work using callbacks. For example, the integer module would hook ADD and MUL instructions to find locations that can overflow, while also hooking JUMPI and SSTORE to find if the values are used there.

This means that analysis and execution happen simultaneously and we don't do any double work

### Benefits
- Only need to keep the last state of a path in memory, rather than needing to keep a copy of all historical states at each instruction

child of #203

[[[MYTHC-3]](https://diligence.atlassian.net/browse/MYTHC-3)](https://diligence.atlassian.net/browse/MYTHC-3)

**Comment by JoranHonig** [comment]
Initially, we should let laser retain the passed states. 
Doing this will allow the current analysis modules to keep working, making their transition easier.

**Comment by JoranHonig** [comment]
This implementation also requires the taint analysis to be changed

**Comment by FFengIll** [comment]
Some extra suggestion: (for I am doing some work like it)
Makes stack element as a individual class like Slot/Element or something.
The possible benefits are:
* python `magic` to override some operators, e.g. __add__, __lt___ and so on
```python
class Slot:
    def __iadd__(self,other):
       #inplace add
       self.value = self.value + other.value
       return self.
```
* python `property` to insulate solver and some others, e.g. (main)
```python
if type(condi) == BoolRef
# can be changed to
if condi.is_bool_ref()
```
* make it possible to use mythril but work for another vm / bytecode (minor)
* may more

I am not sure which one is the better, but wish to have a quick discuss.

**Comment by JoranHonig** [comment]
After a lot of triaging I built the following example code that has the same problem:
```
pragma solidity ^0.4.16;
/**
 * @title SafeMath
 * @dev Math operations with safety checks that throw on error
 */
library SafeMath {
  function sub(uint256 a, uint256 b) internal constant returns (uint256) {
    assert(b <= a);
    return a - b;
  }

  function add(uint256 a, uint256 b) internal constant returns (uint256) {
    uint256 c = a + b;
    assert(c >= a);
    return c;
  }
}

contract IntegerOverflow2  {
    using SafeMath for uint256;
    uint256 public count = 7;
    mapping(address => uint256) balances;


     function run(uint256 input, uint256 _value, address[] _receivers) public {
         uint256 cnt = 5;

         for (uint i = 0; i < cnt; i++) {
             balances[_receivers[i]] = balances[_receivers[i]].add(_value);
//             balances[_receivers[i]] += _value;
         }

         count *= input;

         assert(false);
    }
}

```

The multiply instruction and assert don't seem to be reached wen using add vs +=

**Comment by JoranHonig** [comment]
@FFengIll I'm very sorry, I totally missed your message, (my previous message seems to be posted in the wrong place). Thanks for sharing your idea! (unfortunately the `quick` part didn't really work out)
I agree with you that abstracting the bit vectors in general (not just elements on the stack) would help with defining such properties. This is actually currently in #677
