### ISSUE TITLE
Improve Tracking of Detection Capabilities

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril-classic#240]
Currently we have the [detection capabilities Wiki page](https://github.com/ConsenSys/mythril/wiki/Mythril-Detection-Capabilities). However, this is not comprehensive and not actively maintained.

This task involves the following:

1. Finalize this list to make sure it covers all known vulnerability classes with short descriptions;
2. Link each class to the respective tests in @suhabe's [benchmark suite](https://github.com/ConsenSys/evm-analyzer-benchmark-suite) for each vulnerability class. 
3. Define a process for keeping the list updated.

An idea for the future would be to integrate benchmark suite  into our own CircleCI test suite so the vulnerability coverage report can be auto-generated, but it needs to be more complete first.

**Comment by b-mueller** [comment]
Note:  @birdofpreyru this is a potential TopCoder challenge but needs smart contract security know-how.

**Comment by birdofpreyru** [comment]
@b-mueller it is a bit tricky to wrap into a challenge update of this list, as reviewing submissions, most probably, will take more efforts that just doing it well by a person who knows the issues.

Anyway, soon we gonna have the results of challenges we run to find an extra person to take care about `myrhil` repo. It looks like a good challenge for him.

**Comment by JoranHonig** [comment]
I propose that we change the current wiki page so that we structure the detection capabilities like this:
```
## [Integer Overflow](wikiurl)
Short description of the vulnerability
## [Double send](wikiurl)
Short description of the vulnerability
```
Rendered
## [Integer Overflow](wikiurl)
Short description of the vulnerability
## [Double send](wikiurl)
Short description of the vulnerability

In this case the wikiurls would point to other wiki pages built in #225, which will contain detailed information on the vulnerability, how to fix it, how the module works etc.

**Comment by birdofpreyru** [comment]
@JoranHonig better do with a simple list, like:
```
- [Integer Overflow](wikiurl) &ndash; Short description of the vulnerability
- [Double Send](wikiurl) &ndash; Short description of the vulnerabilty.
```
IMHO, it will be even more convenient:

- [Integer Overflow](wikiurl) &ndash; Short description of the vulnerability
- [Double Send](wikiurl) &ndash; Short description of the vulnerabilty.

**Comment by b-mueller** [comment]
Both ok for me :)

**Comment by JoranHonig** [comment]
I'll go with the one @birdofpreyru  proposed. That will probably be less cluttered

**Comment by rocky** [comment]
> Link each class to the respective tests in @suhabe's benchmark suite for each vulnerability class.

This links to a wiki page. Should  that be a link to some code? 

One thing that scares simple-minded me when someone refers to a  "benchmark" is that this code is complex. For explanation purposes though I think I want "simple". 

We link to ethereum best practices which is good. and those examples are simple.

In some cases there is a full contract as in the case of  https://consensys.github.io/smart-contract-best-practices/recommendations/#handle-errors-in-external-calls

I cut and pasted the the "bad" contract into a truffle project. It would be fantastic if we had in mythril a folder of example _truffle_ projects that contained the bad examples. For example one might be called "handle-errors-in-external calls" with a comment to a link to the relevant ethereum best practice.

In some cases though there is not a full example as in the case of https://consensys.github.io/smart-contract-best-practices/recommendations/#avoid-state-changes-after-external-calls

Here it would be create to create a full example.

**Comment by b-mueller** [comment]
Some info on @suhabe's benchmark suite is here:

https://github.com/ConsenSys/evm-analyzer-benchmark-suite
https://consensys.net/diligence/evm-analyzer-benchmark-suite/

The test cases are very simple (you can click on the links in the "tool evaluation" table to see them).

We still need more though and Suhabe has been preoccupied with audits most of the time, maybe you can jump in on this as well?

**Comment by rocky** [comment]
> We still need more though and Suhabe has been preoccupied with audits most of the time, maybe you can jump in on this as well?

Absolutely! (In fact, I've been doing this or something like this anyway for myself).

**Comment by b-mueller** [comment]
This is superseded by #513.
