### ISSUE TITLE
Wrong diagnostics of contract

### ISSUE THREAD

**Issue by astudnev** [ConsenSys/mythril-classic#243]
**Describe the bug**

The report of the contract submitted for security test is misleading
First it looks like it shows the lines, not related to the problem 
A reachable exception (opcode 0xfe) has been detected 
to the line
mapping(address => address[]) public instantiations

Second, it does not try to analyse other contracts in the file, which may have problems
[MultiSigWalletWithDailyLimit.sol.txt](https://github.com/ConsenSys/mythril/files/2069762/MultiSigWalletWithDailyLimit.sol.txt)

**To Reproduce**
1. Install mythrill with pip3 install
2. run ~/.local/bin/myth -x MultiSigWalletWithDailyLimit.sol
3. See results

**Expected behavior**

Report on possible security issues with the contract

**Screenshots**
```
~/.local/bin/myth -x MultiSigWalletWithDailyLimit.sol 
==== Integer Overflow  ====
Type: Warning
Contract: MultiSigWalletWithDailyLimitFactory
Function name: create(address[],uint256,uint256)
PC address: 228
A possible integer overflow exists in the function `create(address[],uint256,uint256)`.
The addition or multiplication may result in a value higher than the maximum representable integer.
--------------------
In file: MultiSigWalletWithDailyLimit.sol:528

function create(address[] _owners, uint _required, uint _dailyLimit)
        public
        returns (address wallet)
    {
        wallet = new MultiSigWalletWithDailyLimit(_owners, _required, _dailyLimit);
        register(wallet);
    }

--------------------

==== Integer Overflow  ====
Type: Warning
Contract: MultiSigWalletWithDailyLimitFactory
Function name: create(address[],uint256,uint256)
PC address: 696
A possible integer overflow exists in the function `create(address[],uint256,uint256)`.
The addition or multiplication may result in a value higher than the maximum representable integer.
--------------------
In file: MultiSigWalletWithDailyLimit.sol:532

new MultiSigWalletWithDailyLimit(_owners, _required, _dailyLimit)

--------------------

==== Exception state ====
Type: Informational
Contract: MultiSigWalletWithDailyLimitFactory
Function name: _function_0x57183c82
PC address: 815
A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. 
--------------------
In file: MultiSigWalletWithDailyLimit.sol:16

mapping(address => address[]) public instantiations
```
--------------------

**Desktop (please complete the following information):**
 - OS: Debian

**Additional context**

Attaching the source code of the contract

**Comment by b-mueller** [comment]
Thanks @astudnev!

1. The line mapping for the exception is actually correct:

```
mapping(address => address[]) public instantiations
```

If you define a dynamically sized array as a public state variable,`solc` automatically generates an accessor function which contains an assert to catch out-of-bounds array access.

You're not the first one to find this strange, we'll add this to the soon-to-be-created FAQ.

2. We use the address->line mappings generated by solc. Unfortunately, those mappings aren't always correct.

I'm not sure why `new MultiSigWalletWithDailyLimit(_owners, _required, _dailyLimit)` would contain an integer overflow, but "benign" overflows do sometimes exist in bytecode generated by solc. Maybe @JoranHonig can look into it.

**Comment by astudnev** [comment]
Also i noted that running myth several times on the same contract generate DIFFERENT results. This is the evidence:

```
~/.local/bin/myth -x MultiSigWalletWithDailyLimit.sol 
==== Exception state ====
Type: Informational
Contract: Factory
Function name: _function_0x57183c82
PC address: 469
A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. 
--------------------
In file: MultiSigWalletWithDailyLimit.sol:16

mapping(address => address[]) public instantiations

--------------------


~/.local/bin/myth -x MultiSigWalletWithDailyLimit.sol 
==== Exception state ====
Type: Informational
Contract: MultiSigWalletWithDailyLimitFactory
Function name: _function_0x57183c82
PC address: 815
A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. 
--------------------
In file: MultiSigWalletWithDailyLimit.sol:16

mapping(address => address[]) public instantiations

--------------------

==== Integer Overflow  ====
Type: Warning
Contract: MultiSigWalletWithDailyLimitFactory
Function name: create(address[],uint256,uint256)
PC address: 228
A possible integer overflow exists in the function `create(address[],uint256,uint256)`.
The addition or multiplication may result in a value higher than the maximum representable integer.
--------------------
In file: MultiSigWalletWithDailyLimit.sol:528

function create(address[] _owners, uint _required, uint _dailyLimit)
        public
        returns (address wallet)
    {
        wallet = new MultiSigWalletWithDailyLimit(_owners, _required, _dailyLimit);
        register(wallet);
    }

--------------------

==== Integer Overflow  ====
Type: Warning
Contract: MultiSigWalletWithDailyLimitFactory
Function name: create(address[],uint256,uint256)
PC address: 696
A possible integer overflow exists in the function `create(address[],uint256,uint256)`.
The addition or multiplication may result in a value higher than the maximum representable integer.
--------------------
In file: MultiSigWalletWithDailyLimit.sol:532

new MultiSigWalletWithDailyLimit(_owners, _required, _dailyLimit)

--------------------


```

**Comment by b-mueller** [comment]
Hmm, that's definitely not supposed to happen. A possible explanation is solver timeouts. We'll have to investigate.

**Comment by astudnev** [comment]
I played with various command line parameters, calling myth with the same contract and what i found is:

1) sometimes myth hangs for very long ( more than 5 minutes ) and i have to kill it with Ctrl-C. The sack trace is always the same
2) using parameter --max-depth significantly affect the result and hanging. With --max-depth 8 it shows much more issues, than without the parameter ( which is by default 12 ? )
3) half of diagnostics with max-depth 8 makes no sense, as it points to the line of code that has no described issues
4) the snippets of code in the output sometimes not bound directly to the error found. 

[max-depth8.txt](https://github.com/ConsenSys/mythril/files/2071178/max-depth8.txt)
I attach the log to illustrate

**Comment by JoranHonig** [comment]
@astudnev A lot of improvements have come to mythril, the issue I believe caused the problem should have been fixed. Therefore I'm closing this issue, feel free to open a new one it turns out there is still a problem.

Regarding false positives for overflows, it sometimes happens that the solidity compiler creates intentional overflows. This has been something we are aware of and we're constantly trying to improve this the next one on the line that should provide some improved accuracy is: https://github.com/ConsenSys/mythril-classic/issues/782
