### ISSUE TITLE
Consider EVM instruction EXP in Integer Overflow

### ISSUE THREAD

**Issue by rocky** [ConsenSys/mythril-classic#350]
**Describe the bug**
Mythril doesn't detect overflow by exponentiation.

**To Reproduce**

Create solidity contract: 

```solidity

pragma solidity ^0.4.23;

contract IntegerOverflow {
    uint public count = 2;

    function run(uint256 input) public {
        count = count ** input;
    }
}
```

compile it, and then run `myth` on it.

**Expected behavior**

```
==== Integer Overflow ====
Type: Warning
Contract: IntegerOverflow
Function name: **ambiguous** r
PC address: 174
A possible integer overflow exists in the function `**ambiguous** r`.
The addition, multiplication or exponentiation may result in a value higher than the maximum representable integer.
--------------------
In file: test.sol:1

count = count ** input
```

**Desktop:**
 - OS: Ubuntu
 - Version Bionic

**Comment by rocky** [comment]
Should also include XADD and XSUB. They are more recent opcodes, but do they get generated by Solidity or some other compiler?

**Comment by norhh** [comment]
I am not sure whether z3 does support exp or not,if it doesn't then maybe we can approximately do it as exponent must be less than 256(if base>1) so we can just check for them(base>1, exponent>=256), but it doesn't cover all cases. If we have some killer cpu power then search through all the exponents(2 to 255) and get the corresponding base for the exponent(like base >= (2^256)^(1/val), exponent>=val as constraints) and check for sat.
