### ISSUE TITLE
Reducing warnings in EVM code that isn't direclty/immedialy user controllable

### ISSUE THREAD

**Issue by rocky** [ConsenSys/mythril-classic#411]
## Description

Mythril (or a wrapper to it) should distinguish which instructions are directly under the control of a programmer and which parts are not direclty under programmer control. 

## Background

We get a lot of False positives in code that the programmer can't directly control. Out of bound-exceptions in dynamically generated code I think is one. 

## List
- Public storage arrays #276
- Public Enums #277 
- False Positive when arrays are used as function parameters or return values #389

**Comment by JoranHonig** [comment]
Closing this issue as progress is tracked elsewhere
