### ISSUE TITLE
Revise Laser EVM class interface

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril-classic#413]
## Description

Make laser usage more intuitive by simplifying the interface for adding account. Suggestion:

```
caller_account = svm.Account(caller_address, caller_code)
callee_account = svm.Account(callee_address, callee_code)

laser = svm.LaserEVM()

laser.add_account(caller_account)
laser.add_account(callee_account)

laser.sym_exec(caller_address)
```

I would also argue that laser doesn't need to know about the contract name - the mapping address->contract name should happen outside of laser.

**Comment by JoranHonig** [comment]
@b-mueller wtih #404 you kind of have this. Only you need to do ```laser.world_state.add_account```, personally I find this option a bit more logical since you are changing the world state and not laserEVM.

**Comment by JoranHonig** [comment]
I'll mark this issue as done. Laser has gone through a few changes and should support the functionality proposed (albeit maybe through different endpoints)

Please reopen if you disagree!
