### ISSUE TITLE
Catch "effect-check" pattern in integer overflow detection

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril-classic#417]
## Description

Improve integer overflow detection by not reporting a vulnerability when the overflow is caught by an assert(). 

## Background

The SafeMath function prevents overflows as follows:

```
  /**
  * @dev Adds two numbers, throws on overflow.
  */
  function add(uint256 _a, uint256 _b) internal pure returns (uint256 c) {
    c = _a + _b;
    assert(c >= _a);
    return c;
  }
}
```

Mythril reports an issue here because the addition overflows and the result (`c`) is used in a branch condition (in fact it is the condition that is meant to detect the overflow).

This could be solved by determining whether execution always terminates with an exception if `_a + _b` overflows.

The overall logic would then look similar to this:

![integer](https://user-images.githubusercontent.com/5194767/43709983-83765594-9998-11e8-88c4-3ce8f8cb9c7b.png)

Note: This should be added after the major refactoring work is finished.

**Comment by rocky** [comment]
BTW "result used in a jump condition" needs to be used in the right kind of result condition . If that were not `>=` in the assert, things would change.

**Comment by b-mueller** [comment]
Just noticed that I forgot to label the edges which makes this confusing :)To clarify, upper edge is "yes", lower edge is "no".

**Comment by rocky** [comment]
Also, I'm not totally sure about this but "Result used in jump condition?" might need tracking down of several instructions which might include values on the execution stack.

**Comment by nbanmp** [comment]
```
contract othercontract {
    function get_balance(address _addr) public view returns (uint256) {
        return balanceOf[_addr];
    }
    function set_balance(address _addr, uint256 _value) public {
        require(msg.sender == owner);
        balanceOf[_addr] = _value;
    }
}

function withdraw_entire_balance_except_for_amount(uint256 _amount) external {
    value = OtherContract.get_balance(msg.sender) - _amount;
    OtherContract.set_balance(msg.sender, _amount);
    msg.sender.transfer(value);
}
```
Is the logic missing a case like this? The result is never used except in a transfer.
