### ISSUE TITLE
mythril/myth Docker container: problems with wildcard symbols in paths

### ISSUE THREAD

**Issue by birdofpreyru** [ConsenSys/mythril-classic#474]
![image](https://user-images.githubusercontent.com/20144632/44435780-e683ec80-a5b1-11e8-9a24-eeb1da89f6d3.png)

**Comment by birdofpreyru** [comment]
@JoranHonig I just forgot about it. However, I tried now to run it with the command similar to the one suggested at https://github.com/ConsenSys/mythril-classic/wiki/With-Docker:
```bash
$ docker run -v $(pwd):/tmp -w "/tmp/" mythril/myth -xo json *.sol
```
and it seems to work for me. If you can confirm it works, probably, we can just close the issue?

**Comment by JoranHonig** [comment]
Can confirm, closing this issue :+1:
