### ISSUE TITLE
emit statements being flagged as StateChange

### ISSUE THREAD

**Issue by shashank-srikant** [ConsenSys/mythril-classic#505]
## Description
I was analyzing `StateChange` errors raised by Mythril, and noticed a number of contracts having the following pattern being flagged as a state-change issue.

```
function ownerSafeWithdrawal() external onlyOwner nonReentrant {
        require(fundingGoalReached);
        uint balanceToSend = address(this).balance;
        beneficiary.transfer(balanceToSend);
        emit FundTransfer(beneficiary, balanceToSend, false);
    }
```
Technically, `emit` does change states after the external call `transfer` has been called.
But since it is only logging information, shouldn't the severity of this warning be as minimal as possible?
This also relates to my other query on issues raised by Mythril and their associated severity levels (#504).

## How to Reproduce
`myth -xo json filename`
This issue is seen in `0xfc4a176d1db069c92fa5d673543772dc05d18b10`

## Expected behavior
A state change error being flagged with a distinct severity message signifying it's not as important.

**Comment by b-mueller** [comment]
Hi @shahankhatch, are you referring to the "state change after external call" issue?

I tried to simplify your example and I don't see anything reported,

```
pragma solidity 0.4.24;

contract EmitStateChangeTest {

		address beneficiary = 0xdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef;
 		event FundTransfer(address backer, uint amount, bool isContribution);

		function ownerSafeWithdrawal() external {
	        uint balanceToSend = address(this).balance;
	        beneficiary.transfer(balanceToSend);
	        emit FundTransfer(beneficiary, balanceToSend, false);
	    }

}
```

Mythril: 0.18.11

```console
$ myth -x test.sol 
The analysis was completed successfully. No issues were detected.
```

**Comment by shashank-srikant** [comment]
i see; that's odd. Will check and let you know.

**Comment by JoranHonig** [comment]
@shashank-srikant the problem seems to be resolved so I'm closing this issue. If it turns out that this was not the case, please reopen this!
