### ISSUE TITLE
Do reachability check on branch in laser svm

### ISSUE THREAD

**Issue by JoranHonig** [ConsenSys/mythril-classic#509]
If we have some kind of branch in the cfg we should prune unreachable branches.
Right now we only prune branches where the condition simplifies to True

**Comment by norhh** [comment]
Ah!, this was the reason why it took wayy too long time to run when i removed some unnecessary constraints in the integer module( kind of #232 ) and ran on some contracts. Time taken quadrapuled(or more than that) because of this. So this should be done before the independence optimization.

**Comment by norhh** [comment]
you will mostly be focusing on the API for the few weeks right? In that case can I pick this up?

**Comment by JoranHonig** [comment]
Sure, go ahead

**Comment by norhh** [comment]
Looks like z3, does something while solving the previous constraints which makes it much faster cumulatively over solving all the set of constraints entirely. but we need to use timeouts right, so i am not sure how that changes the results. hence i will be doing some benchmarking before setting up the PR.
