### ISSUE TITLE
False positive on ether_send analysis

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril-classic#516]
## Description

Withdrawal of Ether is wrongly reported in the following contract:

```
contract Crowdfunding {

  mapping(address => uint) public balances;
  address public owner;
  uint256 INVEST_MIN = 1 ether;
  uint256 INVEST_MAX = 10 ether;

  modifier onlyOwner() {
    require(msg.sender == owner);
    _;
  }

  function Crowdfunding() {
    owner = msg.sender;
  }

  function withdrawfunds() onlyOwner {
    msg.sender.transfer(this.balance);
  }

  function invest() public payable {
    require(msg.value > INVEST_MIN && msg.value < INVEST_MAX);

    balances[msg.sender] += msg.value;
  }

  function getBalance() public constant returns (uint) {
    return balances[msg.sender];
  }

}
```
## How to Reproduce

```
$MYTH -x constructor_correctly_named.sol 
==== Ether send ====
Type: Warning
Contract: Crowdfunding
Function name: withdrawfunds()
PC address: 713
In the function `withdrawfunds()` a non-zero amount of Ether is sent to msg.sender.
It seems that this function can be called without restrictions.
--------------------
In file: constructor_correctly_named.sol:19

msg.sender.transfer(this.balance)

--------------------
```

## Expected behavior

"Ether send" should not be reported here because the `onlyOwner` checks the caller against the owner, and owner is correctly initialized during construction.

## Environment

Please modify for your setup

- Mythril version: Master
- Solidity compiler and version:  0.4.24+commit.e67f0147.Darwin.appleclang
- Python version: Python 3.6.3
- OS and Version: Mac OS High Sierra

## Additional Environment or Context

Opposite of #515 :)

**Comment by mmhh1910** [comment]
As far as I can see the false positive is reported, because there is no constraint for "caller != creator" in ether_send.py, like there is e.g. in suicide.py.

**Comment by JoranHonig** [comment]
@mmhh1910 Yes you are right! almost have a fix ready ^^'. 
This issue is closely related to #515, and is caused by recent changes/improvements in laser.
