### ISSUE TITLE
Gas Simulation

### ISSUE THREAD

**Issue by norhh** [ConsenSys/mythril-classic#520]
## Description

Simulate Gas for EVM.
## Tests
Add the corresponding [EVM tests](https://github.com/ethereum/tests) which test gas

**Comment by dmuhs** [comment]
According to the [beige paper](https://github.com/chronaeon/beigepaper), there are three cases that influence the gas value:
- computation of an operation
- payments for subordinate message calls/ contract creations
- an increase of memory usage

With the latter, there's also an option to be reimbursed if your transaction frees up storage. This excess value is added to the unused gas value at the end of the tx, so it doesn't influence execution. From the yellow paper it seems that resetting a storage slot also costs gas, so we'll have something like this:
`R_sclear + G_sreset = 15000 - 5000 = 10000`, which is the (apparently fixed) reimbursement for clearing a storage slot.

Steps would be to
- Add used gas, the [tx gas limit](https://ethereum.stackexchange.com/questions/39401/how-do-you-calculate-gas-limit-for-transaction-with-data-in-ethereum) to the transaction model
- Add the gas value in each instruction
- Provide a decorator (or update the state transition one) to check for OOG errors

Spent some time on the tx models today, let's see how far this goes.
Maybe some test cases to check gas usage would also be nice. Did I miss anything? @norhh
