### ISSUE TITLE
Random search strategy

### ISSUE THREAD

**Issue by JoranHonig** [ConsenSys/mythril-classic#539]
## Description
Laser currently implements two basic search strategies, namely bfs and dfs.
However from literature we know that other seach strategies can be more effective. 

### Requirements

Implentation of three search strategies.
1. Each iteration pick a random element from the worklist
2. Each iteration pick a random element from the worklist but elements that are deeper in the statespace should be chosen with less likeliness. 
3. Each iteration consider a statespace described by the traces that lead to the open states. Start from the beginning node and at each node randomly pick one branch to follow until you reach an open state

**Comment by norhh** [comment]
@JoranHonig can you elaborate on what to do when an open state is reached?
