### ISSUE TITLE
Mythril Installation Error on Ubuntu

### ISSUE THREAD

**Issue by Arwinjd** [ConsenSys/mythril-classic#565]
I'm installing Myhtril via pypi on Ubuntu 18.04 and I keep getting this error:

`pip3 install mythril
Collecting mythril
  Using cached https://files.pythonhosted.org/packages/f8/46/c8cac9bf90cbdd7a63125446ba0f96e17c423317d3d589cabbe418e24507/mythril-0.18.12.tar.gz
Requirement already satisfied: configparser>=3.5.0 in /usr/local/lib/python3.6/dist-packages (from mythril) (3.5.0)
Requirement already satisfied: coverage in /usr/local/lib/python3.6/dist-packages (from mythril) (4.5.1)
Collecting eth-account>=0.1.0a2 (from mythril)
  Downloading https://files.pythonhosted.org/packages/a3/d8/6118bc0e00d6ec092bb02b012989d1018893755eb84da53266412ac359e3/eth_account-0.3.0-py3-none-any.whl
Requirement already satisfied: eth-hash>=0.1.0 in /usr/local/lib/python3.6/dist-packages (from mythril) (0.2.0)
Collecting eth-keyfile>=0.5.1 (from mythril)
  Downloading https://files.pythonhosted.org/packages/eb/a5/3615d100b62fbf20fe5d5c0d1d4d7326eac861d260b0cd2a36af2bf8ccb1/eth_keyfile-0.5.1-py3-none-any.whl
Collecting eth-keys>=0.2.0b3 (from mythril)
  Downloading https://files.pythonhosted.org/packages/9b/96/bec507291a2ecac65358b4485282ce02e8c0cdd30980a232791b355a1f5b/eth_keys-0.2.0b3-py3-none-any.whl
Collecting eth-rlp>=0.1.0 (from mythril)
  Downloading https://files.pythonhosted.org/packages/56/4b/b309fb44dd9bb975e84f3d626392eec1eeed0108e55a51cd7dd8956a73ad/eth_rlp-0.1.2-py3-none-any.whl
Collecting eth-tester>=0.1.0b21 (from mythril)
  Using cached https://files.pythonhosted.org/packages/ce/fe/2c31120840f049e04ea4ad45d6ffe3ef96eb86e01b7b6430ca8206343f09/eth_tester-0.1.0b33-py3-none-any.whl
Requirement already satisfied: eth-typing<2.0.0,>=1.3.0 in /usr/local/lib/python3.6/dist-packages (from mythril) (1.3.0)
Collecting eth-utils>=1.0.1 (from mythril)
  Downloading https://files.pythonhosted.org/packages/97/35/6e41ccfecfdd422bb386f186c7288a3176af29d380419645723f5f0b534f/eth_utils-1.2.2-py3-none-any.whl
Collecting eth_abi>=1.0.0 (from mythril)
  Downloading https://files.pythonhosted.org/packages/3d/4e/66d711f39c892c295cd61d2a241d26e4fa253e483382bdb34e39ea4c4d96/eth_abi-1.2.0-py3-none-any.whl
Collecting ethereum>=2.3.2 (from mythril)
  Using cached https://files.pythonhosted.org/packages/ca/48/bd2484ff00fad56bfabad46af8d91f0ab4c6844e389e00b00c7609b405e0/ethereum-2.3.2.tar.gz
Requirement already satisfied: jinja2>=2.9 in /usr/lib/python3/dist-packages (from mythril) (2.10)
Collecting mock (from mythril)
  Using cached https://files.pythonhosted.org/packages/e6/35/f187bdf23be87092bd0f1200d43d23076cee4d0dec109f195173fd3ebc79/mock-2.0.0-py2.py3-none-any.whl
Collecting persistent>=4.2.0 (from mythril)
  Downloading https://files.pythonhosted.org/packages/0f/8f/32da15d94d35ccdfd44c3876ffbe54cf1d594d57db0dc35e17ad9d03aba5/persistent-4.4.2-cp36-cp36m-manylinux1_x86_64.whl (197kB)
    100% |████████████████████████████████| 204kB 2.0MB/s 
Collecting plyvel (from mythril)
  Downloading https://files.pythonhosted.org/packages/10/c2/6f991e5cbd82b458042add518ce80926c40d79a148dcb0fb7ce2e7c3b084/plyvel-1.0.5-cp36-cp36m-manylinux1_x86_64.whl (588kB)
    100% |████████████████████████████████| 593kB 4.7MB/s 
Collecting py-flags (from mythril)
  Using cached https://files.pythonhosted.org/packages/0b/84/9dac0652068c2901f56d37797eb2c303befdafc5f5131f041951b7c86e22/py_flags-1.1.2-py3-none-any.whl
Collecting py-solc (from mythril)
  Using cached https://files.pythonhosted.org/packages/47/74/d36abca3f36ccdcd04976c50f83502c870623e5beb4a4ec96c7bad4bb9e8/py_solc-3.2.0-py3-none-any.whl
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from mythril) (2.18.4)
Collecting rlp>=1.0.1 (from mythril)
  Downloading https://files.pythonhosted.org/packages/98/88/6276aea1ded17ee6db53cc03a80bebdd9c71291dd29e65582314b4bc92fd/rlp-1.0.3-py2.py3-none-any.whl
Collecting transaction>=2.2.1 (from mythril)
  Using cached https://files.pythonhosted.org/packages/2e/fb/e4fd7f99e2349c86275037fa5ddd9a3700174df4779e6fd4b61408726f75/transaction-2.2.1-py2.py3-none-any.whl
Collecting z3-solver>=4.5 (from mythril)
  Using cached https://files.pythonhosted.org/packages/df/3a/c31287d0520bd288cccd336618fae9271b3c4ac22efb360eaa0c533f5db5/z3_solver-4.8.0.0.post1-py2.py3-none-manylinux1_x86_64.whl
Collecting hexbytes<1,>=0.1.0 (from eth-account>=0.1.0a2->mythril)
  Downloading https://files.pythonhosted.org/packages/18/bd/21697d93ee2153c8c12253262b740f571e94341d4cee411504032fff3f56/hexbytes-0.1.0-py3-none-any.whl
Collecting attrdict<3,>=2.0.0 (from eth-account>=0.1.0a2->mythril)
  Downloading https://files.pythonhosted.org/packages/35/bb/bac3e42ae04bc082c28cd8186bfb5b50fb240a4f7419f876c683125ccc8b/attrdict-2.0.0.tar.gz
Collecting cytoolz<1.0.0,>=0.9.0 (from eth-keyfile>=0.5.1->mythril)
  Downloading https://files.pythonhosted.org/packages/36/f4/9728ba01ccb2f55df9a5af029b48ba0aaca1081bbd7823ea2ee223ba7a42/cytoolz-0.9.0.1.tar.gz (443kB)
    100% |████████████████████████████████| 450kB 2.4MB/s 
Collecting pycryptodome<4.0.0,>=3.4.7 (from eth-keyfile>=0.5.1->mythril)
  Downloading https://files.pythonhosted.org/packages/40/83/f195ab14348cc957d5cc6ae195918b1ce012ce2df4f4b9a52e260a8e3ed0/pycryptodome-3.6.6-cp36-cp36m-manylinux1_x86_64.whl (7.4MB)
    100% |████████████████████████████████| 7.4MB 2.1MB/s 
Collecting semantic-version<3.0.0,>=2.6.0 (from eth-tester>=0.1.0b21->mythril)
  Using cached https://files.pythonhosted.org/packages/28/be/3a7241d731ba89063780279a5433f5971c1cf41735b64a9f874b7c3ff995/semantic_version-2.6.0-py3-none-any.whl
Requirement already satisfied: toolz<1,>0.8.2 in /usr/local/lib/python3.6/dist-packages (from eth-utils>=1.0.1->mythril) (0.9.0)
Collecting parsimonious==0.8.0 (from eth_abi>=1.0.0->mythril)
  Downloading https://files.pythonhosted.org/packages/4a/89/32c55944cd30dff856f16859ee325b13c83c260d0c56c0eed511e8063c87/parsimonious-0.8.0.tar.gz
Requirement already satisfied: PyYAML in /usr/lib/python3/dist-packages (from ethereum>=2.3.2->mythril) (3.12)
Collecting coincurve>=7.0.0 (from ethereum>=2.3.2->mythril)
  Downloading https://files.pythonhosted.org/packages/8d/6a/760b5a35d98ab17e0beb39631741b0acd435b85e4279e86937796e670e47/coincurve-9.0.0-cp36-cp36m-manylinux1_x86_64.whl (521kB)
    100% |████████████████████████████████| 522kB 3.7MB/s 
Collecting future (from ethereum>=2.3.2->mythril)
  Using cached https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz
Collecting pbkdf2 (from ethereum>=2.3.2->mythril)
  Using cached https://files.pythonhosted.org/packages/02/c0/6a2376ae81beb82eda645a091684c0b0becb86b972def7849ea9066e3d5e/pbkdf2-1.3.tar.gz
Collecting py_ecc (from ethereum>=2.3.2->mythril)
  Using cached https://files.pythonhosted.org/packages/c9/49/6e07c459f57a497ebc69a98f6975289f5300bc3f05f7c0cc11c8272214a9/py_ecc-1.4.3.tar.gz
Collecting pyethash<1.0.0,>=0.1.27 (from ethereum>=2.3.2->mythril)
  Using cached https://files.pythonhosted.org/packages/6c/40/5bb02ad7e2fae9b04cd0c391dda81213bc786c30c8381b018600cfc7ce62/pyethash-0.1.27.tar.gz
Collecting pysha3>=1.0.1 (from ethereum>=2.3.2->mythril)
  Downloading https://files.pythonhosted.org/packages/32/2a/b93e0c6d90c7c45e2fab35d7ef349e8c5bd7387a048e961b041fd9521556/pysha3-1.0.2-cp36-cp36m-manylinux1_x86_64.whl (127kB)
    100% |████████████████████████████████| 133kB 1.3MB/s 
Collecting repoze.lru (from ethereum>=2.3.2->mythril)
  Using cached https://files.pythonhosted.org/packages/b0/30/6cc0c95f0b59ad4b3b9163bff7cdcf793cc96fac64cf398ff26271f5cf5e/repoze.lru-0.7-py3-none-any.whl
Collecting scrypt (from ethereum>=2.3.2->mythril)
  Using cached https://files.pythonhosted.org/packages/01/6f/3c8dd0f18f73ceddfbdd606c0c895ebb66748606682d77da3743c7c0c56f/scrypt-0.8.6.tar.gz
Collecting pbr>=0.11 (from mock->mythril)
  Using cached https://files.pythonhosted.org/packages/01/0a/1e81639e7ed6aa51554ab05827984d07885d6873e612a97268ab3d80c73f/pbr-4.3.0-py2.py3-none-any.whl
Requirement already satisfied: six>=1.9 in /usr/lib/python3/dist-packages (from mock->mythril) (1.11.0)
Requirement already satisfied: zope.interface in /usr/lib/python3/dist-packages (from persistent>=4.2.0->mythril) (4.3.2)
Collecting dictionaries==0.0.1 (from py-flags->mythril)
  Using cached https://files.pythonhosted.org/packages/4d/54/b45e79bcfb116b7f946cb91f3955618b01a1f80dc0ee85da0d68fcc5f318/dictionaries-0.0.1-py2.py3-none-any.whl
Collecting cffi>=1.3.0 (from coincurve>=7.0.0->ethereum>=2.3.2->mythril)
  Downloading https://files.pythonhosted.org/packages/6d/c0/47db8f624f3e4e2f3f27be03a93379d1ba16a1450a7b1aacfa0366e2c0dd/cffi-1.11.5-cp36-cp36m-manylinux1_x86_64.whl (421kB)
    100% |████████████████████████████████| 430kB 2.8MB/s 
Requirement already satisfied: asn1crypto in /usr/lib/python3/dist-packages (from coincurve>=7.0.0->ethereum>=2.3.2->mythril) (0.24.0)
Collecting pycparser (from cffi>=1.3.0->coincurve>=7.0.0->ethereum>=2.3.2->mythril)
Building wheels for collected packages: mythril, ethereum, attrdict, cytoolz, parsimonious, future, pbkdf2, py-ecc, pyethash, scrypt
  Running setup.py bdist_wheel for mythril ... done
  Stored in directory: /home/beginner/.cache/pip/wheels/ae/00/6d/1ffa77893cf8554fbf677bb049d55d844d352d1c4d2b47590e
  Running setup.py bdist_wheel for ethereum ... done
  Stored in directory: /home/beginner/.cache/pip/wheels/f8/ab/96/2581d17710b5c7b7b3b91dfa7ad604eadd55e9bfbd5d8c089c
  Running setup.py bdist_wheel for attrdict ... done
  Stored in directory: /home/beginner/.cache/pip/wheels/5d/38/d6/303964f4b7e7dc2ef8d00dc028c0e357942fd5a2f34cf6dd30
  Running setup.py bdist_wheel for cytoolz ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ovi6dt1s/cytoolz/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-v5hfbcqx --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/cytoolz
  copying cytoolz/_signatures.py -> build/lib.linux-x86_64-3.6/cytoolz
  copying cytoolz/utils_test.py -> build/lib.linux-x86_64-3.6/cytoolz
  copying cytoolz/compatibility.py -> build/lib.linux-x86_64-3.6/cytoolz
  copying cytoolz/__init__.py -> build/lib.linux-x86_64-3.6/cytoolz
  copying cytoolz/_version.py -> build/lib.linux-x86_64-3.6/cytoolz
  creating build/lib.linux-x86_64-3.6/cytoolz/curried
  copying cytoolz/curried/operator.py -> build/lib.linux-x86_64-3.6/cytoolz/curried
  copying cytoolz/curried/exceptions.py -> build/lib.linux-x86_64-3.6/cytoolz/curried
  copying cytoolz/curried/__init__.py -> build/lib.linux-x86_64-3.6/cytoolz/curried
  copying cytoolz/functoolz.pyx -> build/lib.linux-x86_64-3.6/cytoolz
  copying cytoolz/utils.pyx -> build/lib.linux-x86_64-3.6/cytoolz
  copying cytoolz/itertoolz.pyx -> build/lib.linux-x86_64-3.6/cytoolz
  copying cytoolz/dicttoolz.pyx -> build/lib.linux-x86_64-3.6/cytoolz
  copying cytoolz/recipes.pyx -> build/lib.linux-x86_64-3.6/cytoolz
  copying cytoolz/__init__.pxd -> build/lib.linux-x86_64-3.6/cytoolz
  copying cytoolz/dicttoolz.pxd -> build/lib.linux-x86_64-3.6/cytoolz
  copying cytoolz/functoolz.pxd -> build/lib.linux-x86_64-3.6/cytoolz
  copying cytoolz/utils.pxd -> build/lib.linux-x86_64-3.6/cytoolz
  copying cytoolz/recipes.pxd -> build/lib.linux-x86_64-3.6/cytoolz
  copying cytoolz/itertoolz.pxd -> build/lib.linux-x86_64-3.6/cytoolz
  copying cytoolz/cpython.pxd -> build/lib.linux-x86_64-3.6/cytoolz
  creating build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_embedded_sigs.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/dev_skip_test.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_utils.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_dev_skip_test.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_serialization.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_functoolz.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_compatibility.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_inspect_args.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_docstrings.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_signatures.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_none_safe.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_doctests.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_curried_toolzlike.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_recipes.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_curried.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_dicttoolz.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_tlz.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  copying cytoolz/tests/test_itertoolz.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
  running build_ext
  building 'cytoolz.dicttoolz' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/cytoolz
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c cytoolz/dicttoolz.c -o build/temp.linux-x86_64-3.6/cytoolz/dicttoolz.o
  cytoolz/dicttoolz.c:17:10: fatal error: Python.h: No such file or directory
   #include "Python.h"
            ^~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for cytoolz
  Running setup.py clean for cytoolz
  Running setup.py bdist_wheel for parsimonious ... done
  Stored in directory: /home/beginner/.cache/pip/wheels/bb/51/82/ae9b22a790f11e7be918939d01aa397c545ebb3723453c5fb4
  Running setup.py bdist_wheel for future ... done
  Stored in directory: /home/beginner/.cache/pip/wheels/bf/c9/a3/c538d90ef17cf7823fa51fc701a7a7a910a80f6a405bf15b1a
  Running setup.py bdist_wheel for pbkdf2 ... done
  Stored in directory: /home/beginner/.cache/pip/wheels/8e/62/b9/0bf3a68f2111e169253ec4d2bbdc303c46777b7fc99bbbf230
  Running setup.py bdist_wheel for py-ecc ... done
  Stored in directory: /home/beginner/.cache/pip/wheels/85/bc/65/097ff3cfac9ec05ac56da590d9e9d49d4c54202239aada72a0
  Running setup.py bdist_wheel for pyethash ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ovi6dt1s/pyethash/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-vuc1ol6y --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  building 'pyethash' extension
  creating build
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/src
  creating build/temp.linux-x86_64-3.6/src/python
  creating build/temp.linux-x86_64-3.6/src/libethash
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c src/python/core.c -o build/temp.linux-x86_64-3.6/src/python/core.o -Isrc/ -std=gnu99 -Wall
  src/python/core.c:1:10: fatal error: Python.h: No such file or directory
   #include <Python.h>
            ^~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pyethash
  Running setup.py clean for pyethash
  Running setup.py bdist_wheel for scrypt ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ovi6dt1s/scrypt/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-r5qyqqjb --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/scrypt
  copying scrypt/scrypt.py -> build/lib.linux-x86_64-3.6/scrypt
  copying scrypt/__init__.py -> build/lib.linux-x86_64-3.6/scrypt
  running build_ext
  building '_scrypt' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/src
  creating build/temp.linux-x86_64-3.6/scrypt-1.2.1
  creating build/temp.linux-x86_64-3.6/scrypt-1.2.1/lib
  creating build/temp.linux-x86_64-3.6/scrypt-1.2.1/lib/crypto
  creating build/temp.linux-x86_64-3.6/scrypt-1.2.1/lib/scryptenc
  creating build/temp.linux-x86_64-3.6/scrypt-1.2.1/lib/util
  creating build/temp.linux-x86_64-3.6/scrypt-1.2.1/libcperciva
  creating build/temp.linux-x86_64-3.6/scrypt-1.2.1/libcperciva/alg
  creating build/temp.linux-x86_64-3.6/scrypt-1.2.1/libcperciva/crypto
  creating build/temp.linux-x86_64-3.6/scrypt-1.2.1/libcperciva/util
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DHAVE_CONFIG_H -DHAVE_CLOCK_GETTIME=1 -DHAVE_LIBRT=1 -DHAVE_POSIX_MEMALIGN=1 -DHAVE_STRUCT_SYSINFO=1 -DHAVE_STRUCT_SYSINFO_MEM_UNIT=1 -DHAVE_STRUCT_SYSINFO_TOTALRAM=1 -DHAVE_SYSINFO=1 -DHAVE_SYS_SYSINFO_H=1 -D_FILE_OFFSET_BITS=64 -Iscrypt-1.2.1 -Iscrypt-1.2.1/lib -Iscrypt-1.2.1/lib/scryptenc -Iscrypt-1.2.1/lib/crypto -Iscrypt-1.2.1/lib/util -Iscrypt-1.2.1/libcperciva/cpusupport -Iscrypt-1.2.1/libcperciva/alg -Iscrypt-1.2.1/libcperciva/util -Iscrypt-1.2.1/libcperciva/crypto -I/usr/local/include -I/usr/include -I/usr/include/python3.6m -c src/scrypt.c -o build/temp.linux-x86_64-3.6/src/scrypt.o -O2
  src/scrypt.c:28:10: fatal error: Python.h: No such file or directory
   #include <Python.h>
            ^~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for scrypt
  Running setup.py clean for scrypt
Successfully built mythril ethereum attrdict parsimonious future pbkdf2 py-ecc
Failed to build cytoolz pyethash scrypt
Installing collected packages: cytoolz, eth-utils, rlp, hexbytes, eth-rlp, eth-keys, pycryptodome, eth-keyfile, attrdict, eth-account, parsimonious, eth-abi, semantic-version, eth-tester, pycparser, cffi, coincurve, future, pbkdf2, py-ecc, pyethash, pysha3, repoze.lru, scrypt, ethereum, pbr, mock, persistent, plyvel, dictionaries, py-flags, py-solc, transaction, z3-solver, mythril
  Running setup.py install for cytoolz ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ovi6dt1s/cytoolz/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-zuhj8jqq/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/cytoolz
    copying cytoolz/_signatures.py -> build/lib.linux-x86_64-3.6/cytoolz
    copying cytoolz/utils_test.py -> build/lib.linux-x86_64-3.6/cytoolz
    copying cytoolz/compatibility.py -> build/lib.linux-x86_64-3.6/cytoolz
    copying cytoolz/__init__.py -> build/lib.linux-x86_64-3.6/cytoolz
    copying cytoolz/_version.py -> build/lib.linux-x86_64-3.6/cytoolz
    creating build/lib.linux-x86_64-3.6/cytoolz/curried
    copying cytoolz/curried/operator.py -> build/lib.linux-x86_64-3.6/cytoolz/curried
    copying cytoolz/curried/exceptions.py -> build/lib.linux-x86_64-3.6/cytoolz/curried
    copying cytoolz/curried/__init__.py -> build/lib.linux-x86_64-3.6/cytoolz/curried
    copying cytoolz/functoolz.pyx -> build/lib.linux-x86_64-3.6/cytoolz
    copying cytoolz/utils.pyx -> build/lib.linux-x86_64-3.6/cytoolz
    copying cytoolz/itertoolz.pyx -> build/lib.linux-x86_64-3.6/cytoolz
    copying cytoolz/dicttoolz.pyx -> build/lib.linux-x86_64-3.6/cytoolz
    copying cytoolz/recipes.pyx -> build/lib.linux-x86_64-3.6/cytoolz
    copying cytoolz/__init__.pxd -> build/lib.linux-x86_64-3.6/cytoolz
    copying cytoolz/dicttoolz.pxd -> build/lib.linux-x86_64-3.6/cytoolz
    copying cytoolz/functoolz.pxd -> build/lib.linux-x86_64-3.6/cytoolz
    copying cytoolz/utils.pxd -> build/lib.linux-x86_64-3.6/cytoolz
    copying cytoolz/recipes.pxd -> build/lib.linux-x86_64-3.6/cytoolz
    copying cytoolz/itertoolz.pxd -> build/lib.linux-x86_64-3.6/cytoolz
    copying cytoolz/cpython.pxd -> build/lib.linux-x86_64-3.6/cytoolz
    creating build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_embedded_sigs.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/dev_skip_test.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_utils.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_dev_skip_test.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_serialization.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_functoolz.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_compatibility.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_inspect_args.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_docstrings.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_signatures.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_none_safe.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_doctests.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_curried_toolzlike.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_recipes.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_curried.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_dicttoolz.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_tlz.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    copying cytoolz/tests/test_itertoolz.py -> build/lib.linux-x86_64-3.6/cytoolz/tests
    running build_ext
    building 'cytoolz.dicttoolz' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/cytoolz
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c cytoolz/dicttoolz.c -o build/temp.linux-x86_64-3.6/cytoolz/dicttoolz.o
    cytoolz/dicttoolz.c:17:10: fatal error: Python.h: No such file or directory
     #include "Python.h"
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ovi6dt1s/cytoolz/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-zuhj8jqq/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-ovi6dt1s/cytoolz/
`

**Comment by Arwinjd** [comment]
I ran that and this is what I got:

`sudo apt-get install python3-dev`
`Reading package lists... Done`
`Building dependency tree`      
`Reading state information... Done`
`Some packages could not be installed. This may mean that you have`
`requested an impossible situation or if you are using the unstable`
`distribution that some required packages have not yet been created`
`or been moved out of Incoming.`
`The following information may help to resolve the situation:`
`The following packages have unmet dependencies:`
 `python3-dev : Depends: libpython3-dev (= 3.6.5-3ubuntu1) but it is not going to be installed`
               `Depends: python3.6-dev (>= 3.6.5-2~) but it is not going to be installed`
`E: Unable to correct problems, you have held broken packages.`

**Comment by norhh** [comment]
Argh! some serious dependency issue. In that case can you try using our docker image?

**Comment by Arwinjd** [comment]
@norhh I will try that and get back with you!

**Comment by Arwinjd** [comment]
@norhh everything appears to be working well with Docker, but I'm following the instructions to pass a file to the dockerized Mythril. When I run the following code, I get this:

`sudo docker run -v $(pwd):/tmp mythril/myth -x /tmp/ether.sol`
`Solc experienced a fatal error (code 1).`
`/tmp/ether.sol:41:5: Error: Expected ';' but got '}'`
   ` }`
    `^`

What could be causing this? I created an example file called ether.sol containing the code from one the affected Parity Multisig Wallets

**Comment by norhh** [comment]
@Arwinjd , can you send whats there in the lines 40, 41, 42

**Comment by Arwinjd** [comment]
Sure, on lines 40, 41, 42, of the ether.sol file, it contained this:
`_`
   `}`
    `// multi-sig function modifier: the operation must have an intrinsic hash in order`

**Comment by norhh** [comment]
there should "_;" right? in line 40

**Comment by norhh** [comment]
@Arwinjd can you try compiling the contract with solc?

**Comment by Arwinjd** [comment]
@norhh , how would I do that? Are there instructions posted somewhere?

**Comment by norhh** [comment]
just try `solc <filename>` or `solc --bin <filename>`

**Comment by Arwinjd** [comment]
I'm fairly certain that I've installed everything correctly. Here's what I got when I input the info:
 
`$ solc <company.sol>`
`bash: syntax error near unexpected token "newline"`
`$ solc --bin <company.sol>`
`bash: syntax error near unexpected token "newline"`

**Comment by norhh** [comment]
Hi @Arwinjd can you do `solc --bin company.sol` by removing the brackets and tell the output?

**Comment by JoranHonig** [comment]
Hey @Arwinjd this issue is getting stale so I'll close it. If you still have problems please open another issue!

For solc specific problems you might be better of contacting someone on the solidity gitter
