### ISSUE TITLE
Mythril does not return on StandardBounty.sol after several hours

### ISSUE THREAD

**Issue by suhabe** [ConsenSys/mythril-classic#577]
Mythril does not return on StandardBounty.sol after several hours:
https://github.com/Bounties-Network/StandardBounties/blob/develop/contracts/StandardBounty.sol

```
$ python3 --version
Python 3.6.6

$ uname -a
Linux vagrant 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ pip3 search mythril
mythril (0.18.12)  - Security analysis tool for Ethereum smart contracts
  INSTALLED: 0.18.12 (latest)
```

**Comment by JoranHonig** [comment]
The recent version of mythril works using a timeout on the entirety of the analysis (and should return results once that has passed).  So this is not a problem anymore in the most recent release.

Thanks for the report still!
