### ISSUE TITLE
Remove the -l flag dependency for the onchain contract lookup

### ISSUE THREAD

**Issue by norhh** [ConsenSys/mythril-classic#586]
## Description
currently -l flag is being used for getting onchain data of mythril, which might lead to confusion.so remove that dependency.

**Comment by norhh** [comment]
@b-mueller , can you try it with the -l flag? currently it looks like the contract is killed as I am getting a None response for the code.

**Comment by b-mueller** [comment]
Hey @norhh, yep, that fixed it :) As discussed, we I suggest making retrieving storage locations the default behavior when on-chain contracts are analyzed.

**Comment by norhh** [comment]
@b-mueller , should we add a flag to disable the storage lookup then?
