### ISSUE TITLE
Online signature lookup should be off by default

### ISSUE THREAD

**Issue by mmhh1910** [ConsenSys/mythril-classic#590]
## Description

It is not transparent to the user that mythril does online signature lookups against https://www.4byte.directory/. For privacy reasons, this should be off by default and there should be a command argument in cli.py to enable the lookups.

I can create a PR for this, but would like to discuss it first.

**Comment by norhh** [comment]
function signature is just some number like `0x5ab31` right? would anyone hate to send it to a thirdparty?
Also that feature doesn't work unless `ethereum_input_decoder` is present which is optional.I think that should be mentioned as a warning to the user while mythril is executing and it hasn't found the library.
It's up to the user to whether to download it or not as it isn't listed in the dependency.
I think it would be good to have a cli option for online signature lookup as not everyone might have an internet connection when thinking of running mythril.

**Comment by mmhh1910** [comment]
I didn't realize that ethereum_input_decoder needs to be installed for online lookups to work. With that I do not see a huge privacy problem any longer.

**Comment by mmhh1910** [comment]
What do you think about this:

- Add ethereum_input_decoder to requirements.txt, so e.g. it will be available in the Docker container
- Add an cli flag which needs to be set to enable online lookups

**Comment by norhh** [comment]
etheereum_input_decoder was leftoff because everyone decided on not having many dependencies for the project, if the flag is on and ethereum_input_decoder isn't present then let's raise a warning saying it doesn't work unless this is installed.
