### ISSUE TITLE
File outside of allowed directories

### ISSUE THREAD

**Issue by H34D** [ConsenSys/mythril-classic#597]
## Description

If i run myth on our truffle project i get `File outside of allowed directories`. 

```
/Users/sebastian/ocean/keeper-contracts/contracts/auth/OceanAuth.sol:3:1: Error: Source "/Users/sebastian/ocean/keeper-contracts/contracts/OceanMarket.sol" not found: File outside of allowed directories.
import '../OceanMarket.sol';
^--------------------------^
```
I am using the most recent version 18.12. It was working with 18.11.

$ myth -V
Mythril version v0.18.12

## How to Reproduce

clone 
`https://github.com/oceanprotocol/keeper-contracts`

run 
`myth -x --truffle`

I also tried --sold-args "--allow-paths xxx" but got the same results.

## Expected behavior

should output the results

## Environment

macOS 10.13.6

$ python --version
Python 3.7.0

$ pip --version
pip 18.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)

$ solc --version
solc, the solidity compiler commandline interface
Version: 0.4.25+commit.59dbf8f1.Darwin.appleclang

**Comment by norhh** [comment]
Can you try it with the master version of mythril, I think this was fixed previously but not in the release yet.

**Comment by H34D** [comment]
Using:

$ git rev-parse --verify HEAD
cf7c5cfaaa25a1e66bd6ce3d775c5cbbb3b6a096

yielding:

```
$ ./myth -x ../../keeper-contracts/contracts/auth/OceanAuth.sol 
Solc experienced a fatal error (code 1).

../../keeper-contracts/contracts/auth/OceanAuth.sol:3:1: Error: Source "../../keeper-contracts/contracts/OceanMarket.sol" not found: File outside of allowed directories.
import '../OceanMarket.sol';
^--------------------------^
```

**Comment by norhh** [comment]
Hi @H34D, there is something weird happening with solc, as it isn't properly taking the files in different directories. 
A best solution now is to concatenate all the sol files and run mythril in one go on the concatenated file.

**Comment by tina1998612** [comment]
I'm also facing the same problem.

**Comment by ConnorBlockchain** [comment]
Same issue

**Comment by enderphan94** [comment]
Any fix, yet?

**Comment by norhh** [comment]
hey @enderphan94 where is the overflow.sol in your pc?

**Comment by enderphan94** [comment]
@norhh I placed them in /tmp/ as `/tmp/overflow.sol` .

**Comment by norhh** [comment]
@enderphan94  in that case, you have to run `sudo docker run -v $(pwd):/tmp mythril/myth analyze /tmp/tmp/overflow.sol --solv 0.4.15`

**Comment by enderphan94** [comment]
@norhh I got `Cannot import url ("/tmp/tmp/integer_overflow_1.sol"): Unknown exception in read callback. `

**Comment by norhh** [comment]
Can you mention your directory structure in which you are calling docker?
usually it's like this, if `file.sol` is in your current directory then:-
`docker run -v $(pwd):/tmp mythril/myth analyze /tmp/file.sol`

**Comment by enderphan94** [comment]
I did the same thing, I placed the file.sol in my home directory and ran the exact command you've just mentioned. It either returned one of the error I pointed out above. It worked in my past machines though, don't know why it does not work now :(

**Comment by norhh** [comment]
In that case, can you try reinstalling docker?

**Comment by enderphan94** [comment]
I've reinstalled the docker, it does not work

```Downloading static linux binary from https://github.com/ethereum/solidity/releases/download/v0.4.15/solc-static-linux
Executing: wget https://github.com/ethereum/solidity/releases/download/v0.4.15/solc-static-linux -c -O /root/.py-solc/solc-v0.4.15/bin/solc
Checking installed executable version @ /root/.py-solc/solc-v0.4.15/bin/solc
Executing: /root/.py-solc/solc-v0.4.15/bin/solc --version
solc successfully installed at: /root/.py-solc/solc-v0.4.15/bin/solc
mythril.interfaces.cli [ERROR]: Solc experienced a fatal error.

Cannot import url ("/tmp/overflow.sol"): Unknown exception in read callback.

**Comment by enderphan94** [comment]
I've installed the myth by using pip and ran `myth a integer_overflow_1.sol --solv 0.4.15`. It also returns:

```
mythril.interfaces.cli [ERROR]: Solc experienced a fatal error.
Cannot import url ("integer_overflow_1.sol"): File outside of allowed directories
```

**Comment by norhh** [comment]
@enderphan94 thats weird. can you try `solc integer_overflow_1.sol`?

**Comment by norhh** [comment]
And also whats your solc version?

**Comment by enderphan94** [comment]
solc command works well as the resul:

```
macbookpro@ubuntu:~$ solc integer_overflow_1.sol 
integer_overflow_1.sol:6:5: Error: No visibility specified. Did you intend to add "public"?
    function add(uint value) returns (bool){
    ^ (Relevant source part starts here and spans across multiple lines).
integer_overflow_1.sol:13:5: Error: No visibility specified. Did you intend to add "public"?
    function safe_add(uint value) returns (bool){
    ^ (Relevant source part starts here and spans across multiple lines).
```

```
macbookpro@ubuntu:~$ solc --version
solc, the solidity compiler commandline interface
Version: 0.5.11+commit.22be8592.Linux.g++
```

**Comment by norhh** [comment]
Can you try running it on solver 0.4.15 and check, or other option is can you put in the contract?, I will look into it.

**Comment by enderphan94** [comment]
Yes, it works with solv 0.4.15.
