### ISSUE TITLE
Provide an automated way of keeping the code style consistent

### ISSUE THREAD

**Issue by dmuhs** [ConsenSys/mythril-classic#599]
## Description

Provide a pre-commit hook or another automated way to format the code according to a style guideline whenever a developer touches the code.

## Background

There are various parts of the Mythril Classic code base that have vastly different styles - some of them violating PEP8. A code formatter such as [Black](https://github.com/ambv/black) can gently reformat the code guaranteeing non-breaking changes and keep the whole style consistent and improve readability.

**Comment by jeamick** [comment]
Hello @dmuhs , 

Do you mean to get people like before their code the run Black lib to format their code?
Or do you want to have this directly integrated? 
So when someone is committing something, his code is "automatically" formatted and he gets the errors logs?

thanks

**Comment by JoranHonig** [comment]
Can't we have a CI step that tells you if there are any violations in the added code, and you can only merge the pr if there are no violations?
Basically like the unit tests need to be satisfied too

**Comment by dmuhs** [comment]
That's an option:
```
  --check                     Don't write the files back, just return the
                              status.  Return code 0 means nothing would
                              change.  Return code 1 means some files would be
                              reformatted.  Return code 123 means there was an
                              internal error.
```

So we could simply add it as a dependency, run a check with `black --check .` and let the test fail if anything would be reformatted

**Comment by dmuhs** [comment]
Black itself doesn't have a ton of style rules as it mostly fixes redundant brackets, line-breaks or indentation. You can set the max line length, skip replacing single- with double-quoted strings, or numeric underscores like converting `5000000` to `5_000_000` for readability. I could create a branch with black (and some CI stuff) enabled and you can get an impression of the changes. I did it locally and all looks reasonable :+1:
