### ISSUE TITLE
Mythril misses assert violation

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril-classic#616]
## Description

I tried to "cheat" on one of the [CaptureTheEther](https://capturetheether.com) challenges by adding an assert to have Mythril output the desired value. See first line in ` function buy(uint256 numTokens)`:

```solidity
pragma solidity ^0.4.21;

contract TokenSaleChallenge {
    mapping(address => uint256) public balanceOf;
    uint256 constant PRICE_PER_TOKEN = 1 ether;

    function TokenSaleChallenge(address _player) public payable {
        require(msg.value == 1 ether);
    }

    function isComplete() public view returns (bool) {
        return address(this).balance < 1 ether;
    }

    function buy(uint256 numTokens) public payable {

        // assert added to make Mythril compute numTokens such that 
        // numTokens * PRICE_PER_TOKEN == 0:

        assert(numTokens * PRICE_PER_TOKEN != 0);

        require(msg.value == numTokens * PRICE_PER_TOKEN);

        balanceOf[msg.sender] += numTokens;
    }

    function sell(uint256 numTokens) public {
        require(balanceOf[msg.sender] >= numTokens);

        balanceOf[msg.sender] -= numTokens;
        msg.sender.transfer(numTokens * PRICE_PER_TOKEN);
    }
}
```

However Mythril fails to detect that the condition can be violated (i.e. `numTokens * PRICE_PER_TOKEN` can overflown to 0).

## How to Reproduce

```
$ myth -massert -x tokensale-assert.sol 
The analysis was completed successfully. No issues were detected.
```
## Expected behavior

Mythril should detect an assert violation and output the following:

```
calldata_0:  0xd96a094a  // buy(uint256)
calldata_4: 441711766194596082395824375185729628956870974218904739530401550323154944  // 2 ** (256 - 18)
```

Note: It suspected that it has something to do with the `msg.value == 1 ether` requirement in the constructor but it doesn't seem to be the case. 

## Environment

- Mythril version: Master
- Solidity compiler and version:  0.4.24+commit.e67f0147.Darwin.appleclang
- Python version: 3.6.3
- OS and Version: Mac OS Mojave

**Comment by JoranHonig** [comment]
@b-mueller There is no assert module, do you mean -mexceptions ?

**Comment by b-mueller** [comment]
Ahahaa... I should get more sleep...

**Comment by norhh** [comment]
In that case it might be good for mythril to throw an exception right?
