### ISSUE TITLE
False negative on wrongly named constructor

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril-classic#640]
## Description

Mythril fails to report a reachable SUICIDE instruction due to wrongly named constructor in [this sample](https://github.com/ConsenSys/devcon4-playground/blob/master/exercise4/contracts/Ownable.sol). Code:

```solidity
pragma solidity ^0.4.21;

contract Ownable {
    address owner;

    function Owmable() public {
        owner = msg.sender;
    }

    function kill() public {
        require(msg.sender == owner);

        selfdestruct(msg.sender);
    }
}
```

## How to Reproduce

```
$ myth -x Ownable.sol 
The analysis was completed successfully. No issues were detected.
```

## Expected behavior

Mythril should report the reachable SUICIDE and ideally provide the transaction sequence:

1. call Owmable()
2. call kill(()

Tested with master, develop and Pypi 0.18.13.

**Comment by JoranHonig** [comment]
I think this is something that solidity does to protect you from yourself. (if the function name is close enough to Ownable it doesn't seem to create the function)

For the exercise you can just name it Owmership

**Comment by JoranHonig** [comment]
Closing this because it indeed is a true negative
