### ISSUE TITLE
Set default for --max-tx-count to 1

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril-classic#645]
## Description

Set default maximum tx count to 1. IMO this makes  sense with the current architecture because 2 tx causes a large slowdown, while we detect 80% of SWC vulns with single tx (I just invented that number but it should be about right).

Once we have optimized performance, refactored to callbacks, and have a configurable timeout, we can switch the default back to multi-tx.

From a usability perspective, users would usually run 1 tx for quick analysis, and set it to 2 or 3 for a final verification run that may take longer.

**Comment by JoranHonig** [comment]
This has been fixed
