### ISSUE TITLE
List of smart contract vulnerabilities detected by Mythril

### ISSUE THREAD

**Issue by TlxTejaswi** [ConsenSys/mythril-classic#662]
I would request the group members to help me with a complete list of the smart contract vulnerabilities detected by Mythril.

**Comment by norhh** [comment]
This is in some way a [list](https://github.com/ConsenSys/mythril-classic/wiki/Mythril-Detection-Capabilities) of all the vulnerabilities with mythril. If the detection module column is present for that vulnerability then you can consider that mythril detects it.But yes there are some minute exceptions in that.

You can also look into this interesting paper [Smashing smart contracts for fun and real profit](https://github.com/b-mueller/smashing-smart-contracts/blob/master/smashing-smart-contracts-1of1.pdf)

**Comment by JoranHonig** [comment]
Closed in favor of #967, we'll put an updated version of our detection capabilities on read the docs
