### ISSUE TITLE
Incorrect behavior in on-chain analysis

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril-classic#665]
## Description

Mythril behaves incorrectly when analyzing an on-chain instance of [Ownable.sol](https://github.com/ConsenSys/devcon4-playground/blob/master/exercise4/contracts/Ownable.sol) as opposed to the source code.

## How to Reproduce

Analyzing the source produces the correct transaction sequence (call `Ownab1e()`, the `kill()`):

```
$ myth -msuicide --max-transaction-count 2 --verbose-report -x Ownable.sol
==== Unchecked SUICIDE ====
SWC ID: 106
Type: Warning
Contract: Ownable
Function name: kill()
PC address: 308
A reachable SUICIDE instruction was detected. The remaining Ether is sent to the caller's address.

--------------------
In file: Ownable.sol:13

selfdestruct(msg.sender)

--------------------
--------------------
DEBUGGING INFORMATION:

Transaction Sequence: {'2': {'calldata': '0x2f111e8f', 'call_value': '0x0', 'caller': '0x0000000000000000000000000000000000000000000000000000000000000002'}, '3': {'calldata': '0x41c0e1b51010101010', 'call_value': '0x0', 'caller': '0x0000000000000000000000000000000000000000000000000000000000000002'}}
```
Running against an instance deployed on Ropsten seems to miss the constraint on the contract owner:

```
$ myth --rpc infura-ropsten -msuicide --max-transaction-count 2 --verbose-report -xa 0x4d1734ec536e6dafa3d4ceee532d5b5c8d45fe22
==== Unchecked SUICIDE ====
SWC ID: 106
Type: Warning
Contract: 0x4d1734ec536e6dafa3d4ceee532d5b5c8d45fe22
Function name: kill()
PC address: 185
A reachable SUICIDE instruction was detected. The remaining Ether is sent to the caller's address.

--------------------
--------------------
DEBUGGING INFORMATION:

Transaction Sequence: {'1': {'calldata': '0x41c0e1b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5b5', 'call_value': '0x0', 'caller': '0x0000000000000000000000000000000000000000000000000000000000000000'}}
```

## Expected behavior

I would expect Mythril to automatically the constraint on the suicide instruction, and also determine the current value of owner from storage. It should then correctly determine that there exists a tx that changes the owner and a follow-up tx that kills the contract.

## Environment

- Mythril version: v0.19.3
- Solidity compiler and version: 0.4.24+commit.e67f0147.Darwin.appleclang
- Python version:  3.6.3
- OS and Version: Mac OS Mojave

**Comment by norhh** [comment]
looks like multiple transactions aren't executed for onchain contracts, thats one bug as that doesn't seem to fix this.

**Comment by b-mueller** [comment]
> looks like multiple transactions aren't executed for onchain contracts

In that case, the SUICIDE shouldn't be detected at all?

**Comment by norhh** [comment]
yeah, but mythril is saying that as the contract is uninitialized then owner = 0x0 so if the caller is 0x0 then you can execute suicide.

**Comment by b-mueller** [comment]
Ohh ok, so Mythril is actually right 🤣

How about we set the caller to a random address then?

**Comment by norhh** [comment]
It seems that was already taken care of, but there is a small mistake while taking care of that for onchain contracts.
