### ISSUE TITLE
Propertly handle symbolic execution failures (VMException)

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril-classic#681]
## Description

Mythril appears to terminate symbolic execution when a `VMException` is encountered, but there is no indication of an error unless `-v2` is added (or the user notices low coverage).

This behavior is shown with the Wiki example mentioned in #680.

```
$ myth -xila 0xEbFD99838cb0c132016B9E117563CB41f2B02264
The analysis was completed successfully. No issues were detected.
```

## Expected behavior

If possible, resume symbolic execution from a valid earlier state if a `VMException` happens.

Otherwise, warn the user that symbolic execution has failed which may result in low coverage.

**Comment by norhh** [comment]
Usually VMException shouldn't be encountered unless there is something totally wrong with the code. So probably we might need to check whether there is something wrong with the code in the first place.(or we might be raising the VMException in the wrong place)

**Comment by JoranHonig** [comment]
@b-mueller a VmException is an exception triggered in the virtual machine, and is as such "expected behaviour".  For example an out of gas exception.

In this case there was a bug in how stack underflows were detected. I do think that we can improve on the error reporting. Just saying there has been a VmException doesn't help much IMO

**Comment by b-mueller** [comment]
When I reported this Mythril stopped executing when the `VMException` was encountered - after a second or so it ended the execution trace in `-v2` and Mythril proceeded with security analysis even though coverage was only 50%.

Doesn't seem to happen anymore in v0.19.5 though.
