### ISSUE TITLE
Disassembler runtime-code

### ISSUE THREAD

**Issue by JoranHonig** [ConsenSys/mythril-classic#692]
## Description
Currently the `-d` option only outputs the disassembly of the runtime bytecode for a contract.
When using the -c option, the input is automatically assumed to be creation bytecode.
`myth -d -c "0x6060"` therefore returns nothing.

With the addition of supporting both runtime code and creation code we need to add an adaption to support printing the disassembly of both runtime and creation code.

### Requirements:
With the `-d` option enabled mythril should output the disassembly for both runtime bytecode and creation bytecode if both are available

```
Runtime Disassembly:
0 ADD ...
...

Disassembly:
0 ADD ...
...
```

If either one is not provided then only the other should be printed ( this is the case in `myth -d -c "0x6060"`:

```
Disassembly:
0 ADD ...
...
```

**Comment by cryptobarbossa** [comment]
#787
