### ISSUE TITLE
Check if attack scenario is probable

### ISSUE THREAD

**Issue by pippuris** [ConsenSys/mythril-classic#740]
## Description

It would be nice if reporter would check if caller_address is probable
Most of the time (always) its not, as bruteforcing for specific address is "impossible"

**Comment by b-mueller** [comment]
@pippuris can you provide an example where it is possible?

**Comment by b-mueller** [comment]
Hi @pippuris, in Mythril v0.9.18 assumes an *arbitrary* caller address when reporting issues. The attacker is represented as 0xdeadbeefdeadbead(...) which can be replaced by any address. See also [here](https://github.com/b-mueller/scrooge-mcetherface).
