### ISSUE TITLE
Don't report issues when transaction always reverts

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril-classic#782]
## Description

Currently, a number of false positives exist due to the fact that we may report conditions that always result in a revert. For example `SafeMath` uses a "Effects -> Check pattern" where state is reverted after an integer overflow occurs. An example of this can be for [here](https://gist.github.com/mickayz/4d58ed15edc60d301a4f60fe193e1212).

## Requested Feature

With the callback pattern one solution could be to initialize newly discovered issues in an "unconfirmed" issues and change status to "confirmed" once a `STOP` or `RETURN` is reached in a subsequent state. This would require maintaining a list of unconfirmed issues and an additional callback module on `STOP` and `RETURN`.

Exact implementation unknown, I better leave that up to you ;)

**Comment by JoranHonig** [comment]
Is this a duplicate of https://github.com/ConsenSys/mythril-classic/issues/417 ?

**Comment by JoranHonig** [comment]
I already have a neat idea of how to do this using state annotations :+1:

**Comment by b-mueller** [comment]
> Is this a duplicate of #417 ?

Yes, I"ll close that.

**Comment by b-mueller** [comment]
Wow, I just saw that made an awesome diagram in #417!
