### ISSUE TITLE
Refactor: Callback deprecated_ops.py

### ISSUE THREAD

**Issue by JoranHonig** [ConsenSys/mythril-classic#790]
## Description
The delegate call module `mythril/analysis/modules/deprecated_ops.py` should be refactored to work as a callback module.

An example refactored module is `mythril/analysis/modules/suicide.py`

child of #226

**Comment by b-mueller** [comment]
Wie can add a `CALLCODE` here:

https://smartcontractsecurity.github.io/SWC-registry/docs/SWC-111
