### ISSUE TITLE
Not working on macOS 

### ISSUE THREAD

**Issue by eduardonunesp** [ConsenSys/mythril-classic#827]
```
docker run mythril/myth -x contracts/Migrations.sol
Unable to find image 'mythril/myth:latest' locally
latest: Pulling from mythril/myth
32802c0cfa4d: Pull complete
da1315cffa03: Pull complete
fa83472a3562: Pull complete
f85999a86bef: Pull complete
180e5a2c0a92: Pull complete
214cad7dde19: Pull complete
4712ffba65db: Pull complete
030b308f4ee6: Pull complete
c88cfa5f56ce: Pull complete
7f9b377ccaa4: Pull complete
Digest: sha256:ca3cac02080da785166fef1776c162a39331bbd2de28befc7980169345e0f5e3
Status: Downloaded newer image for mythril/myth:latest
mythril.interfaces.cli [ERROR]: Solc has experienced a fatal error (code 1).

"contracts/Migrations.sol" is not found.
```

Docker `Docker version 18.09.0-ce, build 4d60db4`
macOS  `10.14.2`

```docker run mythril/myth --version
Mythril version v0.19.11
```

**Comment by norhh** [comment]
Hi @eduardonunesp , you need to mount that directory into docker before using it. 
In this way `docker run -v $(pwd):/tmp mythril/myth -x /tmp/contracts/Migrations.sol`

**Comment by eduardonunesp** [comment]
It works thanks, ```
docker run -v (pwd):/tmp mythril/myth -x /tmp/contracts/Migrations.sol
mythril.interfaces.cli [ERROR]: Solc has experienced a fatal error (code 1).

/tmp/contracts/Migrations.sol:1:1: Error: Source file requires different compiler version (current compiler is 0.5.1+commit.c8a2cb62.Linux.g++ - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.4.24;```

Can I use a version `0.4.24` or `0.4.25` instead `0.5.1` ?

**Comment by norhh** [comment]
try `--solv <version_name>`

**Comment by eduardonunesp** [comment]
Awesome ! thank you very much !

**Comment by locpv-ibl** [comment]
I ran `sudo docker run -v $(pwd):/tmp mythril/myth -x /tmp/contracts/TokenDistribution.sol`. But it still does not work, it did work before :(

**Comment by locpv-ibl** [comment]
Solved my issue. I have to run the command in /tmp directory :)

**Comment by mansurmasama** [comment]
I have a tmp directory in C:/ called 'sols'. I then used the following code and it didn't work:

docker run -v $(pwd):/sols mythril/myth analyze C:/sols/PolyAi.sol

Any help please.
