### ISSUE TITLE
Run callbacks Asynchronously

### ISSUE THREAD

**Issue by norhh** [ConsenSys/mythril-classic#830]
## Description
As each  callback function's execution is independent of the next execution of the state, we can execute them asynchronously in a separate process.

## Advantages
- Faster execution

## Disadvantages
- Makes things a bit complicated

**Comment by b-mueller** [comment]
Is it really always independent? How about checks that depend on state annotations from earlier invocations of the callback?

**Comment by norhh** [comment]
The main performance bottleneck in the modules is the constraint solving right?. As long as we can parallelize that we might be good.But yes not all modules are totally independent.

**Comment by JoranHonig** [comment]
@norhh Can I close this issue? The effort involved + bernhard's comment indicates that this is probably not worth the effort.
One thing we could look into is using multiple processes for sym exec, but that would be something different
