### ISSUE TITLE
Timeout and max-depth results

### ISSUE THREAD

**Issue by shashank-srikant** [ConsenSys/mythril-classic#836]
In the current version,  hitting either the max-timeout or max-depth limit results in Mythril returning an innocent looking output like this -
`{"error": null, "issues": [], "success": true}`

Can we please have a separate indicator in the output to suggest that the lack of an issue was because of hitting this limit. Currently, there's no real way to distinguish between Mythril genuinely not finding a bug vs. Mythril returning "no error" simply because it hit one of these limits.

This, in my opinion, is quite a critical flag to have in the output. I'm not sure, but i thought i had raised this issue a while back. Thanks.

**Comment by shashank-srikant** [comment]
on a related note, is it possible, in the current release, to run mythril with `--execution-timeout` as 1 second, with it overriding the default `--max-depth` of 22? 

when i try running with a 1 second timeout, mythril still manages to give me results for a contract which it takes ~10 seconds wall-clock time to analyze.

**Comment by norhh** [comment]
`in the current release, to run mythril with --execution-timeout as 1 second, with it overriding the default --max-depth of 22` can you explain it in detail? If you just want to have execution timeout but no max depth then set max-depth to a large value like 500 or 1000. max depth is essential as it gets mythril out of loops with symbolic checks.

**Comment by shashank-srikant** [comment]
I want to run it with the condition -
`min(max-depth, max-timeout)`

When I currently set max timeout to 1 second, mythril still seems to run
more than a second and produces the desired result. Why so?

**Comment by norhh** [comment]
execution timeout is a bit different from the total timeout, it's in our todo list, #673 , what you mentioned will happen quite soon(in a week or 2 at max).

**Comment by shashank-srikant** [comment]
Cool. Thanks.

Also, can we increase the priority of the main issue on this thread to
something more than just an enhancement. It completely invalidates any
analysis when keeping these flags on, as there's no real way to
differentiate bw no errors vs. hitting the constraints.

**Comment by norhh** [comment]
Priority isn't yet added, enhancement is just a category in categories like feature, bug, refactor, ... .

**Comment by norhh** [comment]
In most of the cases(at least 90% of real world contracts) mythril won't halt. whenever there is a loop on a variable in that case mythril doesn't finish, so nearly call contracts don't execute entirely, One way for you to check whether the entire code is covered or not is to view to code coverage of mythril with -v5 logging option.

**Comment by JoranHonig** [comment]
This should be resolved with the many changes leading up to 0.20.0. I'm going to close this issue. 
Feel free to re-open if there are still unresolved problems
