### ISSUE TITLE
Implement the new JSON output format

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril-classic#844]
## Description

Update JSON output to follow the new specification:

```
{
    "issues": [
        {
            "swcID": "",
            "swcTitle": "",
            "description": {
                "head": "", 
                "tail": ""
            },
            "severity": "",
            "locations": [ 
                {
                 "sourceMap": "", 
                }, ...
            ],
            "extra": {} 
        }
    ],
    "sourceType": "", 
    "sourceFormat": ""
    "sourceList": [ "", ... ], 
    "meta": {}
}
```

### Details

**1. When the input is one or more Solidity files return a SourceList as follows:**

```
    "sourceType": "solidity-file", 
    "sourceFormat": "text"
    "sourceList": [ "file1.sol, "file2.sol" ,...]
```
 
Source maps for each issue follow the standard solc format:

```
"sourceMap": "24:693:0"
```

**2. When the input is bytecode (`-c`):**

```
"sourceType": "raw-bytecode"
"sourceFormat": "evm-byzantium-bytecode",
"sourceList": [ "0xeda9b01a853deb0dbc2380aa9c3053529aec777e2aae6818f5819cd5feebb1ff" ],
```

Note that the entries in "sourceList" are sha3 hashes of the contract bytecode(s).

Sourcemap again follows the solc format. Mythril usually only returns a simple bytecode offset per issue, e.g.:

```
"sourceMap": "10"
```

**3. When the input is an Ethereum address bytecode (`-a`):**

Mapping is the same as for raw bytecode but `sourceType` changes to `ethereum-address`.

**Comment by b-mueller** [comment]
>  can you please clarify what the meta field is?And what exactly is extra?

Those two fields can be left empty for now/

> And also does ; appear in source mappings in mythril's case?

I don't think so, it would return a single source map per issue such as "24:693:0".

**Comment by norhh** [comment]
And what is the head and tail in the titles?Are these from swc registry or from our issue statements?
