### ISSUE TITLE
Re-introduce check for state changes after external calls

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril-classic#886]
## Description

Report state changes after external calls. 

## Implementation details

Prior versions of Mythril used to report a warning if a state change after an external call occurred:

```
"The contract account state is changed after an external call. Consider that the called contract could re-enter the function before this state change takes place. This can lead to business logic vulnerabilities."
```

Re-implement this check using state annotations.

## Implementation

Off the top of my head: In the `external_calls` module, Set an annotation on calls and check for the annotation on SSTORE and balance changes.

It could make sense to change severity based on whether the target address can be influenced by the caller (this is already implemented in `external calls.py`). E.g.:

- State change after call to fixed address: Low
- State change after call to user-determined address: Medium

## Link

https://smartcontractsecurity.github.io/SWC-registry/docs/SWC-107#simple-daosol

https://medium.com/chainsecurity/constantinople-enables-new-reentrancy-attack-ace4088297d9

**Comment by b-mueller** [comment]
FYI I implemented this a while ago here:

https://github.com/ConsenSys/mythril-classic/blob/constantinope-reentrancy-check/mythril/analysis/modules/constantinople_bug_2.py

**Comment by yxliang01** [comment]
Yes, +1 for this. Only after this is implemented, you can say Mythrill-classic supports detecting Re-entrancy issue. Currently, it simply reports all External Calls. Correct me if wrong.
