### ISSUE TITLE
Line number to source mapping

### ISSUE THREAD

**Issue by shashank-srikant** [ConsenSys/mythril-classic#929]
What's the easiest way to map Mytrhil errors, returned when running `myth -xo json filename`, to corresponding line numbers in the solidity source provided to it? 

The current line number information provided is noisy.
Previous issues raised related to this seem to be pending -- 
https://github.com/ConsenSys/mythril-classic/issues/395
https://github.com/ConsenSys/mythril-classic/issues/424

**Comment by norhh** [comment]
@shashank-srikant , the solc mapping doesn't seem to be proper. If you want the raw solc src maps so that you can translate it yourself then try `myth -xo jsonv2 filename` , you can find the "sourceMap" field there.

**Comment by shashank-srikant** [comment]
i get an `invalid choice jsonv2` error.
is this flag a recent addition?

**Comment by norhh** [comment]
yes

**Comment by norhh** [comment]
currently waiting on https://github.com/ethereum/solidity/issues/6119

**Comment by shashank-srikant** [comment]
also, i wanted to understand why the srcmaps returned by mythril-classic don't really correspond to any srcmaps present in the AST of the corresponding solidity source.

these maps do correspond to lines, but do not specifically correspond to any existing map listed out in the AST.

**Comment by norhh** [comment]
we directly take the maps from solc's `srcmap` and `srcmap-runtime` options, I didn't think that the solc also gives out mapping for AST(which is cool) .Probably you can check whether the solc's src-map output corresponds to the ast source's output or not.

**Comment by norhh** [comment]
and I think this PR might fix most of the line number problems https://github.com/ConsenSys/mythril-classic/pull/949 , you can try with this PR. or you can clone it from [this](https://github.com/ConsenSys/mythril-classic/tree/bugfix/lineno) branch
