### ISSUE TITLE
Unexpected calldata for functions related to mapping storage and access

### ISSUE THREAD

**Issue by ezulkosk** [ConsenSys/mythril-classic#934]
## Description

Below I've listed a simple contract that has 2 functions:
* `setValue` -- which expects an argument `k` to be equal to `123`, and stores a value in a map at `k`;
* `badFunction` -- which reverts if it can find a stored value in the map greater than zero (i.e., it successfully passes `require(map[k] > 0);` and then reaches `assert(false)`).

The only map index that can be stored at is `123`, therefore the expected reachable-exception should be found by invoking `setValue(123)` followed by `badFunction(123)`. However, the associated calldata for `badFunction`, found in the verbose-report below, corresponds to some other index.

## How to Reproduce

Input contract stored in `MapTest.sol`:
```
pragma solidity ^0.4.0;
contract MapTest{
  mapping(uint256 => uint256) map;

  constructor() public {}

  function setValue(uint256 k) public {
    require(k == 123);
    map[k] = 456;
  }

  function badFunction(uint256 k) public {
    require(k > 0);
    require(map[k] > 0);
    assert(false);
  }
}
```

When invoking `myth -x MapTest.sol --verbose-report` I receive the following trace for a reachable-exception for the `assert false`. The two function signatures correspond to `setValue` followed by `badFunction` as expected; my concern is the last calldata:

```
...
In file: contracts/MapTest.sol:18

assert(false)

--------------------
--------------------
Transaction Sequence:

{
    "2": {
        "calldata": "0x55241077000000000000000000000000000000000000000000000000000000000000007b",
        "call_value": "0x0",
        "caller": "0xdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef"
    },
    "3": {
        "calldata": "0x249a78db0010",
        "call_value": "0x0",
        "caller": "0xdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef"
    }
}
```

## Expected behavior

The `calldata` for the last transaction in the sequence should be `0x249a78db000000000000000000000000000000000000000000000000000000000000007b`, which corresponds to calling `badFunction(123)`.

## Environment

- Mythril version: v0.20.0
- Solidity compiler and version: 0.4.25+commit.59dbf8f1.Darwin.appleclang
- Python version: 3.7.2
- OS and Version: Mac OS Mojave

## Additional Notes
I noticed that in `instructions.py`, when invoking the `sha3_` function, the length value used was 64. Assuming the invocation of `sha3_` corresponds to some access/storage of the mapping, shouldn't the length be 256, since the key to the mapping is a uint256? Perhaps I'm not understanding some of the low-level semantics.

Thanks!

**Comment by norhh** [comment]
Hi @ezulkosk , thanks for raising the bug, currently the Storage can't handle symbolic access properly, we are currently working on it.`the length value used was 64. Assuming the invocation of `sha3_` corresponds to some access/storage of the mapping,` I can't seem to find the length 64 being used there, can you please mention the line number?

**Comment by ezulkosk** [comment]
Hi, thanks for the quick reply.

> the length value used was 64

This wasn't a hardcoded value, but was the result of debugging the `length` value here https://github.com/ConsenSys/mythril-classic/blob/9072be4ad221d3edddd1b24eff2f6d6eca879fc6/mythril/laser/ethereum/instructions.py#L876 .

While investigating the above program, the index was 0 and the length was 64. My intuition/assumptions are the following:
1) The sha3 corresponds to either a map storage/read.
2) The length should(?) correspond to the length of the keccak256 parameter, which is the `uint256 k` parameter, but is instead 64 (bits?).

**Comment by norhh** [comment]
Oh! that part is retreving the data from the memory, The function implements sha3 opcode, which get's data from memory[index:index+length], where each slot in memory supports 256 bit word. So it's 64* 256 bits.

**Comment by ezulkosk** [comment]
Ah, that makes sense. Thanks for the clarification!
