### ISSUE TITLE
False positive: "Integer overflow" issue in ERC20 contract function

### ISSUE THREAD

**Issue by aarthiKannanEY** [ConsenSys/mythril-classic#947]
## Description

Mythril reports Integer overflow issue with the ERC20 "increaseAllowance" function as shown in the audit result below.

## How to Reproduce
Used Mythril with Truffle

```console
$ myth --truffle
==== Exception state ====
# Analysis result for ERC20:

==== Integer Overflow ====
SWC ID: 101
Severity: High
Contract: ERC20
Function name: increaseAllowance(address,uint256)
PC address: 3645
Estimated Gas Usage: 1025 - 1500
The binary addition can overflow.
The operands of the addition operation are not sufficiently constrained. The addition could therefore result in an integer overflow. Prevent the overflow by checking inputs or ensure sure that the overflow is caught by an assertion.
--------------------
In file: ERC20.sol:46

ddres

Solidity Source: "openzeppelin-solidity/contracts/token/ERC20/ERC20.sol"

## Expected behavior

No issues found.

## Environment

- Mythril version: v0.20.0
- Solidity compiler and version: 0.5.4+commit.9549d8ff.Darwin.appleclang
- Python version: 2.7.10
- OS and Version: Mac OS Mojave

**Comment by norhh** [comment]
hi @aarthiKannanEY ,  unfortunately I couldn't generate the same issue, this PR #949 might fix it, can you check it. Currently mythril-cli doesn't go well with truffle and we are planning to remove it in the near future, you can try out [truffle-security](https://github.com/ConsenSys/truffle-security) tool, it runs mythril+various other tools(uses mythx api) in the backend and is pretty cool.

**Comment by JoranHonig** [comment]
@norhh & @aarthiKannanEY 
This seems to be a problem in the mapping logic in our truffle specific code, as @norhh mentioned this functionality is being depricated, so I'm closing this issue.

If you still have this issue using mythril-security then we'd love to hear your feedback!
