### ISSUE TITLE
Fix transaction order dependence module

### ISSUE THREAD

**Issue by norhh** [ConsenSys/mythril-classic#952]
## Description
The transaction order dependence module isn't compatible with the current laser as it still assumes the entire storage as symbolic, That should be fixed

**Comment by JoranHonig** [comment]
this is a duplicate of #860 (I think) so I'm closing this issue

**Comment by norhh** [comment]
I think this issue is to say that tx_order_dependence doesn't even work, Currently mythril-classic doesn't recognize this bug.

**Comment by JoranHonig** [comment]
Both this issue and #860 require the same changes and have the same effect, which is why I closed this one

**Comment by norhh** [comment]
@JoranHonig , this requires rewriting the tx order dependence module, so we can change that issue to do the rewrite and close this
