### ISSUE TITLE
Implement bitwise shifting (EIP 145)

### ISSUE THREAD

**Issue by palkeo** [ConsenSys/mythril-classic#957]
It got live in the last hard fork: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-145.md
But I don't think laser supports it?

Also, solc now generates code that uses these opcodes in every contract, so I think it should get prioritized.

**Comment by norhh** [comment]
@palkeo thanks for the info :+1: , We already have an issue for it(#535 ), we will prioritize it more.
