### ISSUE TITLE
BitVecFunc implementation bug

### ISSUE THREAD

**Issue by JoranHonig** [ConsenSys/mythril-classic#961]
Looking at arithmetic helper in `bitvecfunc.py`

I noticed that the current implementation will assume that:
`F(a+b) = F(a) + b`

**Comment by norhh** [comment]
arthemetic helper is always called from BitVecFunc right? in that case 1st term will be F(a).

**Comment by norhh** [comment]
@JoranHonig If let's say `X = A+B`, If `type(A) == BitVec` and `type(B) == BitVecFunc` . BitVec's `+` is called which seems to do a `B + A` . can you confirm this?

**Comment by JoranHonig** [comment]
I think so, yes

**Comment by norhh** [comment]
So this isn't a bug right?
